# Generated by Django 3.1.4 on 2020-12-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201224_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemedbudget',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
